server:
  port: 2011
eureka:
  client:
    service-url:
      defaultZone: http://peer1:1011/eureka
spring:
  application:
    name: firstProvider
  cloud:
    loadbalancer:
      ribbon:
        enabled: false