spring:
    application:
        name: eureka-consumer
server:
    port: 3011
eureka:
    client:
        serviceUrl:
            defaultZone: http://peer1:1011/eureka/
        register-with-eureka: false