server:
  port: 1012

eureka:
  instance:
    hostname: peer2
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://peer1:1011/eureka/,http://peer2:1012/eureka/,http://peer3:1013/eureka/
