server:
  port: 1011

eureka:
  instance:
    hostname: peer1
    server:
      enable-self-preservation: false
  client:
#    是否向服务注册中心注册自身
    register-with-eureka: false
#    是否检索服务
    fetch-registry: false
    service-url:
      defaultZone: http://peer1:1011/eureka/,http://peer2:1012/eureka/,http://peer3:1013/eureka/
